### ISSUE TITLE
Add code coverage workflow

### ISSUE THREAD

**Issue by Hussein-Mahfouz** [Hussein-Mahfouz/flowcluster#10]
1. Make repo open
2. Add codecoverage workflow

```yaml
name: test-coverage

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test-coverage:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: r-lib/actions/setup-r@v2
      - name: Install dependencies
        run: |
          install.packages('remotes')
          remotes::install_deps(dependencies = TRUE)
          remotes::install_cran('covr')
      - name: Run tests and coverage
        run: |
          Rscript -e 'covr::codecov()'
```

3. Add code coverage badge
    - visit project page on [codecov.io](https://codecov.io/gh/Hussein-Mahfouz/your-repo-name).
    - Click the badge icon and copy the Markdown.
